### ISSUE TITLE
Refresh rate forced to 60hz

### ISSUE THREAD

**Issue by JamatoPecanz** [comp500/BorderlessMining#60] opened 2023-01-14 00:38 UTC
When using borderless mining, the refresh rate of my monitor is automatically set to 60hz.  I have tried adjusting fullscreen resolution to 144hz in the sodium menu, but since borderless mining overrides that it doesn't change anything.

Possible that I'm just missing an obvious solution though.

**Comment by comp500** [comment] 2023-01-16 19:07
What's your desktop refresh rate set to [in your system's settings](https://support.microsoft.com/en-us/windows/change-your-display-refresh-rate-in-windows-c8ea729e-0678-015c-c415-f806f04aae5a)? Are you using a custom resolution configured in the driver?

**Comment by comp500** [comment] 2023-12-22 23:12
Closing: insufficient information to replicate; possibly a duplicate of https://github.com/comp500/BorderlessMining/issues/26

**Closed as not planned by comp500** 2023-12-22 23:12 UTC
Labels: question
