### ISSUE TITLE
removes monitor overclock 

### ISSUE THREAD

**Issue by AHHEUS** [comp500/BorderlessMining#84] opened 2023-08-26 14:02 UTC
i oc my monitor to 75hz when i go fullscreen it drops back down to 60 but it stays 75 when windowed but windowed sucks thats why i use this mod

**Comment by comp500** [comment] 2023-08-26 14:04
Duplicate of https://github.com/comp500/BorderlessMining/issues/26.

**Closed as not planned by comp500** 2023-08-26 14:04 UTC
