### ISSUE TITLE
Game Crashes with Optifine/Optifabric

### ISSUE THREAD

**Issue by PhoGaNgon** [comp500/BorderlessMining#47] opened 2022-07-12 04:15 UTC
When using this mod with the 1.19 Optifine and 1.13.5 Optifabric mods, my game crashes whenever I try to use the chat. This applies to both single and multiplayer.

**Comment by comp500** [comment] 2022-07-12 06:33
Duplicate of #42.

**Closed as not planned** 2022-07-12 06:33 UTC
