### ISSUE TITLE
Update to 1.20.6

### ISSUE THREAD

**Issue by Steame090** [comp500/BorderlessMining#103] opened 2024-05-09 15:21 UTC
Please, make it compatible with 1.20.6

**Comment by pollyevamay** [comment] 2024-05-11 14:01
As far as im aware it already does work, atleast for me. I dont think it has been updated on modrinth and curseforge to say it works tho. You should just be able to manually download the mod and put it in your mods folder

**Comment by aoqia194** [comment] 2024-05-20 14:18
You can track the merge progress on my PR here: #106

**Comment by comp500** [comment] 2024-05-27 18:04
Duplicate of #90

**Closed as not planned by comp500** 2024-05-27 18:04 UTC
