### ISSUE TITLE
Minecraft crashes when opening options menu

### ISSUE THREAD

**Issue by PeerkeG** [comp500/BorderlessMining#48] opened 2022-07-13 09:41 UTC
When I'm using the borderless mining mod, and try to open the options menu (either in-game or the home screen) Minecraft crashes. Tried to isolate the problem by removing all of my mods, and adding them 1 by 1, and found out it was the borderless mining which caused the issue

I added the crash log

[crash-2022-07-13_11.24.56-client.txt](https://github.com/comp500/BorderlessMining/files/9100932/crash-2022-07-13_11.24.56-client.txt)

**Comment by Hammey0** [comment] 2022-07-14 03:02
I am getting the same issue trying to open with options menu with borderless mining + optifabric and optifine. I can open the options menu just fine if I run sodium instead of optifabric with optifine

**Comment by comp500** [comment] 2022-07-14 22:02
Duplicate of https://github.com/comp500/BorderlessMining/issues/42.

**Closed as not planned by comp500** 2022-07-14 22:02 UTC
