### ISSUE TITLE
Game crashes when opening the options menu

### ISSUE THREAD

**Issue by JTM712** [comp500/BorderlessMining#45] opened 2022-07-10 00:16 UTC
Essentially what the title says.
It says:

> The game crashed whilst mouseclicked event handler
> Error: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_446 failed
> Exit Code: -1

And the crash report is attached
[crash-2022-07-09_17.14.01-client.txt](https://github.com/comp500/BorderlessMining/files/9078142/crash-2022-07-09_17.14.01-client.txt)

**Comment by comp500** [comment] 2022-07-10 00:18
Likely duplicate of #42 and #43; please report this issue to Optifabric instead.

**Closed as completed by comp500** 2022-07-10 00:18 UTC
