### ISSUE TITLE
Unable to use xbox game bar

### ISSUE THREAD

**Issue by TechPro424** [comp500/BorderlessMining#37] opened 2022-06-12 09:42 UTC
Even when in fullscreen and with this mod installed, I can't use xbox game bar
It tells me to choose fullscreen borderless in the game settings when I already have it chosen in the mod menu settings screen for the mod

**Comment by comp500** [comment] 2022-06-12 12:11
Duplicate of #3; please try #19 as it appears to fix this issue

**Closed as completed** 2022-06-12 12:11 UTC
